package com.assetsphere.modules.audit.domain;

public enum AuditAction {
    USER_REGISTERED, USER_LOGIN_SUCCEEDED, USER_LOGIN_FAILED, USER_LOGGED_OUT,
    WORKSPACE_CREATED, WORKSPACE_UPDATED, WORKSPACE_MEMBER_INVITED,
    WORKSPACE_INVITATION_ACCEPTED, WORKSPACE_MEMBER_ROLE_CHANGED, WORKSPACE_MEMBER_REMOVED
}
