import {
  ArrowRight, BrainCircuit, Check, DatabaseZap, Facebook, FileStack, Github, GitCompareArrows,
  History, Instagram, Layers, Linkedin, LockKeyhole, MessageSquareQuote, RefreshCw, Search, ShieldCheck, UploadCloud,
} from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { publicLinks } from "@/config/public-links";
import { usePlans } from "@/features/billing/hooks";
import { formatBytes } from "@/lib/utils";

const features = [
  [ShieldCheck, "Secure workspaces", "Keep team knowledge inside authorized, workspace-isolated boundaries."],
  [History, "Versioned assets", "Advance important documents while preserving every earlier source version."],
  [BrainCircuit, "AI intelligence", "Generate summaries, key points, and tags only when your team asks."],
  [Search, "Semantic + hybrid retrieval", "Find exact language and conceptually relevant evidence together."],
  [MessageSquareQuote, "Grounded answers", "Ask questions and keep citations connected to trusted workspace sources."],
  [RefreshCw, "Reliable processing", "Extraction, indexing, retries, and failure handling run asynchronously."],
] as const;

const workflow = [
  [UploadCloud, "Upload"], [History, "Version"], [BrainCircuit, "Understand"],
  [Search, "Search"], [MessageSquareQuote, "Ask with citations"],
] as const;

const trust = ["Idempotent uploads", "Transactional outbox", "Retries + dead-letter handling", "Workspace isolation", "Complete version history", "Grounded AI outputs"];

export function LandingPage() {
  const plans = usePlans();
  const socials = [
    [Linkedin, "LinkedIn", publicLinks.linkedin], [Github, "GitHub", publicLinks.github],
    [Instagram, "Instagram", publicLinks.instagram], [Facebook, "Facebook", publicLinks.facebook],
  ] as const;
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-30 border-b border-border/80 bg-background/90 backdrop-blur-xl"><nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8" aria-label="Primary navigation"><Link to="/" className="flex items-center gap-2.5 rounded-md font-semibold"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary"><Layers className="h-4 w-4 text-primary-foreground" /></span>AssetSphere</Link><div className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#product" className="hover:text-foreground">Product</a><a href="#features" className="hover:text-foreground">Features</a><a href="#architecture" className="hover:text-foreground">Security</a></div><div className="flex gap-2"><Button variant="ghost" asChild><Link to="/login">Sign in</Link></Button><Button asChild><Link to="/register">Get started</Link></Button></div></nav></header>
    <main>
      <section className="overflow-hidden border-b border-border bg-muted/20"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-1 text-xs font-medium text-primary"><GitCompareArrows className="h-3.5 w-3.5" /> Evolution-aware knowledge</div><h1 className="mt-6 max-w-3xl text-4xl font-semibold tracking-[-0.035em] sm:text-6xl sm:leading-[1.05]">Your knowledge changes.<br /><span className="text-primary">AssetSphere understands what changed.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Securely upload, version, understand, retrieve, and ask grounded questions across the knowledge your team depends on.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link to="/register">Get started <ArrowRight className="h-4 w-4" /></Link></Button><Button size="lg" variant="outline" asChild><a href="#product">Explore how it works</a></Button></div></div><ProductFlow /></div></section>

      <section id="product" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">One connected workflow</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">From source file to cited answer.</h2><p className="mt-4 leading-7 text-muted-foreground">AssetSphere treats knowledge as a living system—not a pile of disconnected uploads.</p></div><div className="mt-12 grid gap-3 md:grid-cols-5">{workflow.map(([Icon, label], index) => <div key={label} className="relative rounded-xl border border-border bg-card p-5 text-center shadow-sm"><div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10"><Icon className="h-4 w-4 text-primary" /></div><p className="mt-3 text-sm font-semibold">{label}</p>{index < workflow.length - 1 && <ArrowRight className="absolute -right-3 top-1/2 z-10 hidden h-5 w-5 -translate-y-1/2 rounded-full bg-background text-muted-foreground md:block" />}</div>)}</div></section>

      <section id="features" className="border-y border-border bg-muted/25"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Why AssetSphere</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Enterprise knowledge without the enterprise clutter.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, description]) => <article key={title} className="rounded-xl border border-border bg-background p-6"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted"><Icon className="h-4 w-4 text-primary" /></div><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></article>)}</div></div></section>

      <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:items-center lg:py-28"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Evolution Intelligence</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Understand the evolution, not just the latest file.</h2><p className="mt-5 text-base leading-7 text-muted-foreground">Compare any two versions of the same asset and surface the executive summary, additions, removals, key changes, and decisions that matter.</p><div className="mt-6 space-y-3">{["Exact-version intelligence stays accessible", "Comparisons run only when explicitly requested", "Every result remains scoped to the authorized asset"].map((item) => <div key={item} className="flex gap-3 text-sm"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-primary/10"><Check className="h-3 w-3 text-primary" /></span>{item}</div>)}</div></div><div className="rounded-2xl border border-primary/20 bg-primary/[.035] p-6 shadow-xl shadow-primary/5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><GitCompareArrows className="h-5 w-5 text-primary" /><span className="text-sm font-semibold">Evolution Intelligence</span></div><span className="rounded bg-background px-2 py-1 text-[10px] font-semibold uppercase text-muted-foreground">On demand</span></div><div className="mt-6 flex items-center gap-3"><VersionPill label="Version 2" /><ArrowRight className="h-4 w-4 text-muted-foreground" /><VersionPill label="Version 3" /></div><div className="mt-5 space-y-3">{["Executive change summary", "New and removed knowledge", "Important shifts highlighted"].map((item) => <div key={item} className="rounded-lg border border-border bg-background px-4 py-3 text-sm text-muted-foreground">{item}</div>)}</div></div></section>

      <section id="architecture" className="bg-sidebar text-sidebar-foreground"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-sidebar-accent"><LockKeyhole className="h-5 w-5 text-sidebar-accent-foreground" /></div><h2 className="mt-5 text-3xl font-semibold text-white">Built to stay dependable when workflows get real.</h2><p className="mt-4 leading-7 text-sidebar-muted-foreground">Production-minded foundations keep uploads, processing, versions, and AI actions predictable without turning the product into developer tooling.</p></div><div className="grid gap-3 sm:grid-cols-2">{trust.map((item) => <div key={item} className="flex items-center gap-3 rounded-lg border border-sidebar-border bg-sidebar-muted/50 px-4 py-3 text-sm"><DatabaseZap className="h-4 w-4 text-sidebar-accent-foreground" />{item}</div>)}</div></div></div></section>

      <section className="mx-auto max-w-4xl px-5 py-20 text-center sm:px-8 lg:py-24"><FileStack className="mx-auto h-8 w-8 text-primary" /><h2 className="mt-5 text-3xl font-semibold tracking-tight">Give changing knowledge a system that keeps up.</h2><p className="mt-4 text-muted-foreground">Start a workspace, upload the first asset, and preserve what your team learns next.</p><div className="mt-7 flex justify-center gap-3"><Button size="lg" asChild><Link to="/register">Get started <ArrowRight className="h-4 w-4" /></Link></Button><Button size="lg" variant="outline" asChild><Link to="/login">Sign in</Link></Button></div></section>
      <PricingSection plans={plans.data} loading={plans.isLoading} />
    </main>
    <footer className="border-t border-border"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:grid-cols-[1fr_auto] sm:px-8"><div><Link to="/" className="inline-flex items-center gap-2 font-semibold"><Layers className="h-4 w-4 text-primary" />AssetSphere</Link><p className="mt-2 text-xs text-muted-foreground">Version-aware enterprise knowledge.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><a href="#product">Product</a><a href="#features">Features</a><a href="#architecture">Security / Architecture</a><Link to="/login">Sign in</Link><Link to="/register">Get started</Link></div></div>{socials.some(([, , url]) => Boolean(url)) && <div className="mx-auto flex max-w-7xl gap-3 border-t border-border px-5 py-5 sm:px-8">{socials.map(([Icon, label, url]) => url ? <a key={label} href={url} target="_blank" rel="noreferrer" aria-label={label} className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Icon className="h-4 w-4" /></a> : null)}</div>}</footer>
  </div>;
}

function ProductFlow() { return <div className="rounded-2xl border border-border bg-card p-5 shadow-2xl shadow-slate-950/10"><div className="flex items-center justify-between border-b border-border pb-4"><span className="text-xs font-semibold">Knowledge workflow</span><span className="flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-status-ready" />Connected</span></div><div className="mt-4 space-y-3">{workflow.map(([Icon, label], index) => <div key={label} className="flex items-center gap-3 rounded-xl border border-border bg-background p-3.5"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-muted"><Icon className="h-4 w-4 text-primary" /></span><div className="flex-1"><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{["Secure source asset", "Preserved history", "On-demand AI insights", "Lexical + semantic retrieval", "Grounded response with citations"][index]}</p></div><span className="text-xs font-medium text-muted-foreground">0{index + 1}</span></div>)}</div></div>; }
function VersionPill({ label }: { label: string }) { return <span className="rounded-lg border border-border bg-background px-4 py-2 text-sm font-semibold">{label}</span>; }

function PricingSection({ plans, loading }: { plans: import("@/types/billing").PlanResponse[] | undefined; loading: boolean }) {
  return <section id="pricing" className="border-t border-border bg-muted/20"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-8"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Plans</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Start focused. Scale when your workspace needs more.</h2><p className="mt-4 text-muted-foreground">Entitlements shown directly from AssetSphere&apos;s enforced plan catalog.</p></div>{loading && <div className="mt-10 grid gap-4 lg:grid-cols-3">{[0,1,2].map((item) => <div key={item} className="h-64 animate-pulse rounded-xl bg-muted" />)}</div>}{plans && <div className="mt-10 grid gap-4 lg:grid-cols-3">{plans.map(({ plan, entitlements }) => <article key={plan} className={`flex rounded-xl border bg-background p-7 ${plan === "PRO" ? "border-primary/40 shadow-lg shadow-primary/5" : "border-border"}`}><div className="flex w-full flex-col"><div className="flex items-center justify-between"><h3 className="text-2xl font-semibold">{plan}</h3>{plan === "PRO" && <span className="rounded bg-primary/10 px-2 py-1 text-[10px] font-semibold uppercase text-primary">More capacity</span>}</div>{plan === "ENTERPRISE" && <p className="mt-2 text-sm font-semibold text-primary">CUSTOM pricing</p>}<ul className="mt-6 flex-1 space-y-3 text-sm text-muted-foreground">{[`${entitlements.maxAssets} assets`, `${entitlements.maxMembers} members`, `${formatBytes(entitlements.maxStorageBytes)} storage`, `${entitlements.monthlyAiInsights} AI insights monthly`, `${entitlements.monthlyAskRequests} Ask requests monthly`, "Semantic + hybrid search", ...(entitlements.ocrEnabled ? ["OCR"] : []), ...(entitlements.videoTranscriptionEnabled ? ["Video transcription"] : [])].map((item) => <li key={item} className="flex gap-2"><Check className="h-4 w-4 shrink-0 text-primary" />{item}</li>)}</ul>{plan === "ENTERPRISE" ? <Button className="mt-7 w-full" variant="outline" disabled>Contact Sales</Button> : <Button className="mt-7 w-full" variant={plan === "PRO" ? "default" : "outline"} asChild><Link to="/register">Get started</Link></Button>}</div></article>)}</div>}</div></section>;
}
